### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by peteristhegreat** [vavarachen/splunk_http_handler#7]
I'm using this package on a flask website (thank you for posting it), and my splunk server apparently needs some retries with the HEC adapter.

Here are the raw stack traces:
```
Error: Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
six.raise_from(e, None)
File "", line 3, in raise_from
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.8/http/client.py", line 1322, in getresponse
response.begin()
File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.8/http/client.py", line 272, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 400, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
six.raise_from(e, None)
File "", line 3, in raise_from
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.8/http/client.py", line 1322, in getresponse
response.begin()
File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.8/http/client.py", line 272, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/app/app/server.py", line 507, in my_function
logger.info({"filename": downloaded_file, "username": session[constants.PROFILE_KEY]['nickname'], "file_contents": json_data})
File "/usr/local/lib/python3.8/logging/__init__.py", line 1434, in info
self._log(INFO, msg, args, **kwargs)
File "/usr/local/lib/python3.8/logging/__init__.py", line 1577, in _log
self.handle(record)
File "/usr/local/lib/python3.8/logging/__init__.py", line 1587, in handle
self.callHandlers(record)
File "/usr/local/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
hdlr.handle(record)
File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
self.emit(record)
File "/usr/local/lib/python3.8/site-packages/splunk_hec_handler/__init__.py", line 193, in emit
req = self.r.post(self.url, data=data, timeout=self.TIMEOUT)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

This stackoverflow post makes it look like it just needs more retries to work:

https://stackoverflow.com/questions/33895739/python-requests-module-error-cant-load-any-url-remote-end-closed-connection

Thanks for any thoughts while I am looking for a solution.  Right now all my logging calls are wrapped with:

```
import traceback

try:
    logging.info("Some message")
except Exception:
    flash("Error: \n{}\n".format(traceback.format_exc().replace('\n', '<br />')), "warning")
```

as my work around.

**Comment by peteristhegreat** [comment]
I found a reasonable fix for it: https://stackoverflow.com/a/63641442/999943

I just finished posting the pull request.  Thanks!

**Comment by vavarachen** [comment]
@peteristhegreat, the issue might be related to an overly aggressive 'TIMEOUT' value of '2' used by the module.  I plan to make this value configurable and change the default to something more reasonable like 30 seconds in the near future.

https://github.com/vavarachen/splunk_hec_handler/pull/8#issuecomment-683799054

**Comment by vavarachen** [comment]
@peteristhegreat , thanks for contribution.  Merged.
